In [3]:
import cv2
import numpy as np

cv2.__version__

'4.10.0'

In [9]:
img = cv2.imread("opencv-logo.png") # load image

In [15]:
cv2.namedWindow("Image", cv2.WINDOW_NORMAL) #prepare viewing window

In [17]:
cv2.imshow("image", img) #display image

In [19]:
cv2.waitKey(0) 

27

In [21]:
cv2.imwrite("output.jpg", img) # create new copy of image with cv

True

In [25]:
img2 = cv2.imread("opencv-logo.png", 1) #load image in color

In [27]:
img2

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [29]:
type(img)

numpy.ndarray

In [31]:
len(img) # rows

739

In [33]:
len(img[0]) # cols

600

In [35]:
len(img[0][0]) # channels

3

In [37]:
img.shape

(739, 600, 3)

In [39]:
img.dtype

dtype('uint8')

In [41]:
img[10, 5]

array([255, 255, 255], dtype=uint8)

In [43]:
img[:,:,0]

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [45]:
img.size

1330200

Module 3


In [47]:
black = np.zeros([150, 200, 1],'uint8')

In [49]:
cv2.imshow("Black",black)
print(black[0,0,:])

[0]


In [55]:
ones = np.ones([150,200,3],'uint8')
cv2.imshow("Ones",ones)
print(ones[0,0,:])

[1 1 1]


In [59]:
white = np.ones([150,200,3],'uint16')
white *= (2**16 - 1)
cv2.imshow("White", white)
print(white[0,0,:])

[65535 65535 65535]


In [63]:
color = ones.copy()
color[:,:] = (255,0,0)
cv2.imshow("Blue",color)
print(color[0,0,:])

[255   0   0]


In [65]:
cv2.waitKey(0)
cv2.destroyAllWindows()

Module 4

In [75]:

color = cv2.imread("butterfly.jpg",1)
cv2.imshow("Image",color)
cv2.moveWindow("Image",0,0)
print(color.shape)
height,width,channels = color.shape


(356, 493, 3)


In [77]:
b,g,r = cv2.split(color)

rgb_split = np.empty([height,width*3,3],'uint8')

rgb_split[:, 0:width] = cv2.merge([b,b,b])
rgb_split[:,width:width*2] = cv2.merge([g,g,g])
rgb_split[:, width*2:width*3] = cv2.merge([r,r,r])

cv2.imshow("Channels", rgb_split)
cv2.moveWindow("Channels",0,height)

In [81]:
hsv = cv2.cvtColor(color, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split(hsv)
hsv_split = np.concatenate((h,s,v),axis=1)
cv2.imshow("Split HSV", hsv_split)

In [83]:
cv2.waitKey(0)
cv2.destroyAllWindows()

 Module 5

In [85]:
gray = cv2.cvtColor(color, cv2.COLOR_RGB2GRAY)
cv2.imwrite("gray.jpg", gray)


True

In [25]:
b = color[:,:,0]
g = color[:,:,1]
r = color[:,:,2]

rgba = cv2.merge((b,g,r,g))
cv2.imwrite("rgba.png",rgba)

NameError: name 'color' is not defined

Module 6

In [5]:
image = cv2.imread("thresh.jpg")
cv2.imshow("Original", image)


In [9]:
blur = cv2.GaussianBlur(image, (5,55), 0)
cv2.imshow("Blur",blur)


In [13]:
kernel = np.ones((5,5),'uint8')
dilate = cv2.dilate(image, kernel, iterations=1)
erode = cv2.erode(image, kernel, iterations=1)
cv2.imshow("Dilate", dilate)
cv2.imshow("Erode", erode)

In [15]:
cv2.waitKey(0)
cv2.destroyAllWindows()

Module 7

In [17]:
img3 = cv2.imread("players.jpg", 1)

In [21]:
img_half = cv2.resize(img3, (0,0), fx = 0.5, fy = 0.5)
img_stretch = cv2.resize(img3, (600,600))
img_stretch_near = cv2.resize(img3, (600,600), interpolation = cv2.INTER_NEAREST)

In [23]:
cv2.imshow("Half", img_half)
cv2.imshow("Stretch", img_stretch)
cv2.imshow("Stretch near", img_stretch_near)



In [33]:
M = cv2.getRotationMatrix2D((0,0), -30,1)
rotated = cv2.warpAffine(img3, M, (img3.shape[1], img3.shape[0]))
cv2.imshow("Rotated", rotated)

In [35]:
cv2.waitKey(0)
cv2.destroyAllWindows()

Module 8 and 9

In [61]:
cap = cv2.VideoCapture(0)

In [62]:
color = (0,255,0)
line_width = 3
radius = 100
point = (0,0)

In [63]:
def click(event, x, y, flags, param):
    global point, pressed
    if event == cv2.EVENT_LBUTTONDOWN:
        print("Pressed", x, y)
        point = (x,y)

In [64]:
cv2.namedWindow("Frame")
cv2.setMouseCallback("Frame",click)

In [69]:
while(True):
    ret, frame = cap.read()

    frame = cv2.resize(frame, (0,0), fx=0.5, fy=0.5)
    cv2.circle(frame, point, radius, color, line_width)
    cv2.imshow("Frame", frame)

    ch = cv2.waitKey(1)
    if ch & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

Pressed 135 141
Pressed 182 137
Pressed 180 125
Pressed 165 123
Pressed 178 118
Pressed 157 158
Pressed 142 177
Pressed 152 106
Pressed 174 65
Pressed 212 119
Pressed 143 167
Pressed 160 119
Pressed 121 180
Pressed 259 117
Pressed 309 122
Pressed 309 122
Pressed 308 123
Pressed 126 131
Pressed 97 131
Pressed 73 83
Pressed 135 64
Pressed 274 101
Pressed 291 149
Pressed 228 198
Pressed 124 200
Pressed 93 184
Pressed 102 100
Pressed 164 70
Pressed 259 87
Pressed 269 161
Pressed 222 216
Pressed 134 226
Pressed 51 179
Pressed 80 94
Pressed 165 88
Pressed 252 109
Pressed 241 191
Pressed 177 222
Pressed 70 209
Pressed 61 140
Pressed 119 92
Pressed 198 105
